### ISSUE TITLE
Feature Request: Validate that `.info.yml` contains modules from which classes or functions are used

### ISSUE THREAD

**Issue by Kingdutch** [mglaman/phpstan-drupal#247]
In larger projects it's possible that modules are already enabled and thus that a class exists. However, it's possible that when the module being worked on is installed in a different project that the dependency isn't actually there.

It would be great since PHPStan knows what classes and functions are used and where they come from that it can check based on the namespace or path that the module to which the class or function belongs is in the `.info.yml` file of the module that's using it.

**Comment by mglaman** [comment]
@Kingdutch what level are you running PHPStan at? Because this should "just work" if running at higher levels. If you're only doing deprecation checks (drupal-check, upgrade_status) that isn't even `level: 0`. It is a custom runner.

**Comment by Kingdutch** [comment]
We're running [PHPStan at level 8](https://github.com/goalgorilla/open_social/blob/main/phpstan.neon#L5), although we do have an [extensive baseline](https://github.com/goalgorilla/open_social/blob/main/phpstan-baseline.neon). I didn't see any of the warnings I'd expect in the baseline.

I'm not sure I explained correctly. If the feature is implemented I would, using Open Social as example, [a use of a class from `social_core` in `social_user`](https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_user/src/Entity/User.php#L5) to emit an error if [`social_core` is not listed as dependency](https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_user/social_user.info.yml). Such error is not currently part of PHPStan Drupal as far as I could find.

**Comment by mglaman** [comment]
@Kingdutch oh! so try to report that you're accessing namespaces which _may not actually_ be available at runtime.

I think this got up before. Because right now this projects consumes all possible namespaces. So an idea would be to allow configuring what modules should be scanned – either manually or scanning the `core.extensions.yml`.

It sounds like that is what you need. I think it's smarter to try and parse `core.extensions.yml` than to make someone manually track in `phpstan.neon` and equally dangerous to become out of date

**Comment by Kingdutch** [comment]
Not entirely! I think that's what I saw in #4 ?

I don't want to change the PHPStan configuration. What I want PHPStan to tell me is "Hey this module A is using code from this other module B, but the module A doesn't tell Drupal (using A's .info.yml file) that B is a dependency, that's an error".

**Comment by mglaman** [comment]
Ah, now I understand! Detecting if a dependent namespace is not available because its dependency on it is not declared.

I think that might be feasible but also very complex.

The first step would be https://github.com/mglaman/phpstan-drupal/issues/249, so we can easily get information about the current extension. The Extension object should have the dependencies list.

Then we need to determine what nodes to listen on

* MethodCall
* StaticCall
* StaticPropertyFetch
* New_

BUT! What about when modules have a `ModuleHandlerInterface::moduleExists` check? That might be hard to determine.

See this JSON:API module dynamic injection from content_moderation, which it exists:

https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/modules/jsonapi/jsonapi.services.yml#L154

```yaml
  # Access Control
  jsonapi.entity_access_checker:
    class: Drupal\jsonapi\Access\EntityAccessChecker
    public: false
    arguments: ['@jsonapi.resource_type.repository', '@router.no_access_checks', '@current_user', '@entity.repository']
    calls:
      # This is a temporary measure. JSON:API should not need to be aware of the Content Moderation module.
      - [setLatestRevisionCheck, ['@?access_check.latest_revision']] # This is only injected when the service is available.
```

So when `setLatestRevisionCheck` is checked, it'll throw an error when it shouldn't.

In all honestly, I think it would be worth adding and folks can ignore those errors when relevant and then maybe we can find a way to be smart about it.
