### ISSUE TITLE
Document how contrib modules can define their own entityMapping configuration

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#281]
Thanks to an awesome discussion with @kingdutch, it is possible that contributed projects can provide their own `entityMapping` configuration and reduce the work end-users are required to do.

This requires having `phpstan/extension-installer` added to the root project.

Contributed projects can create an `entity_mapping.neon` file which contains their entity mapping

In their `composer.json`, they just need to add information to the `extra` section to register with the `extension-installer`

```
{
  "extra": {
    "phpstan": {
      "includes": [
        "entity_mapping.neon"
      ]
    }
  }
}
```

Note, it can be any filename.

--- 

Here is a rough example for Drupal Commerce

`entity_mapping.neon`

```
parameters:
  entityMapping:
    commerce_store:
      class: Drupal\commerce_store\Entity\Store
      storage: Drupal\commerce_store\StoreStorage
    commerce_store_type:
      class: Drupal\commerce_store\Entity\StoreType
```

Note: `storage` is not needed for `commerce_store_type` as phpstan-drupal will infer it is a config entity and use that appropriate default storage handler.

`composer.json`

```json
{
    "name": "drupal/commerce",
    "type": "drupal-module",
    "description": "Drupal Commerce is a flexible eCommerce solution.",
    "homepage": "http://drupal.org/project/commerce",
    "license": "GPL-2.0+",
    "require": {
        "php": "^7.3 || ^8.0",
        "ext-bcmath": "*",
        "drupal/core": "^9.2",
        "drupal/address": "^1.7",
        "drupal/entity": "^1.0",
        "drupal/entity_reference_revisions": "~1.0",
        "drupal/inline_entity_form": "^1.0-rc6",
        "drupal/profile": "^1.2",
        "drupal/state_machine": "^1.5",
        "drupal/token": "^1.7",
        "commerceguys/intl": "^1.0.0"
    },
    "require-dev": {
        "drupal/entity_print": "^2.2",
        "drupal/mailsystem": "^4.3"
    },
    "conflict": {
        "drupal/commerce_shipping": "<2.1"
    },
    "minimum-stability": "dev",
    "extra": {
        "phpstan": {
             "includes": ["entity_mapping.neon"]
        }
    }
}
```
