### ISSUE TITLE
Calling getStorage with a constant does not resolve entity mapped storage class

### ISSUE THREAD

**Issue by dpi** [mglaman/phpstan-drupal#299]
Calling getStorage where the first parameter (`$entity_type_id`) is a constant does not resolve the correct storage class.

Given.

```yaml
parameters:
	drupal:
		entityMapping:
			my_custom_config_entity_type:
				class: Drupal\my_custom_config_entity_type\Entity\MyCustomConfigEntityType
				storage: Drupal\Core\Config\Entity\ConfigEntityStorage
```

PHPStan does not resolve the class for getStorage properly when this is called.

```php
$entities = \Drupal::entityTypeManager()->getStorage(MyCustomConfigEntityType::ENTITY_TYPE_ID)->loadMultiple();
```

`$entities` is `\Drupal\Core\Entity\EntityInterface[]`

Expected

`$entities` is `\Drupal\my_custom_config_entity_type\Entity\MyCustomConfigEntityType[]`
