### ISSUE TITLE
Flag \Drupal::VERSION as a dynamic constant

### ISSUE THREAD

**Issue by mglaman** [mglaman/phpstan-drupal#325]
This is what phpstan-symfony does, and prevents irrelevant rules when doing version comparisons

```yaml
parameters:
	dynamicConstantNames:
		- Symfony\Component\HttpKernel\Kernel::VERSION_ID
```
