### ISSUE TITLE
Unknown `drupal` parameter

### ISSUE THREAD

**Issue by claudiu-cristea** [mglaman/phpstan-drupal#528]
<table>
<tr>
	<td>mglaman/phpstan-drupal</td><td>1.1.30</td>
</tr>
<tr>
	<td>phpstan/phpstan</td><td>1.10.13</td>
</tr>
</table>

I'm getting:

`Unexpected item 'parameters › drupal'.`

My phpstan.neon:

```
parameters:
    customRulesetUsed: true
    reportUnmatchedIgnoredErrors: false
    drupal:
        drupal_root: %currentWorkingDirectory%/web
        entityMapping:
            og_membership:
                class: Drupal\og\Entity\OgMembership
                storage: Drupal\Core\Entity\Sql\SqlContentEntityStorage
            rdf_entity:
                class: Drupal\rdf_entity\Entity\Rdf
                storage: Drupal\sparql_entity_storage\SparqlEntityStorage
```

From composer.json:

```
        "phpstan": {
            "includes": [
                "vendor/mglaman/phpstan-drupal/extension.neon",
                "vendor/phpstan/phpstan-deprecation-rules/rules.neon"
            ]
        }
```

and using the `phpstan/extension-installer` plugin
