### ISSUE TITLE
Undefined array key "class"

### ISSUE THREAD

**Issue by mondrake** [mglaman/phpstan-drupal#578]
# Bug report

While playing with service autowiring in https://www.drupal.org/project/drupal/issues/3367416, incurred in the following warning while running PHPStan:

`PHP Warning:  Undefined array key "class" in /var/www/html/vendor/mglaman/phpstan-drupal/src/Drupal/ServiceMap.php on line 50`

**Comment by mglaman** [comment]
Is there no `class` property because the service name is the class?

**Comment by mglaman** [comment]
Weird. This handles if it isn't set or not.

https://github.com/mglaman/phpstan-drupal/blob/main/src/Drupal/ServiceMap.php#L32-L46

**Comment by mglaman** [comment]
I think I may have found it when dealing with inline aliases which also have a parent:

```yaml
  logger.channel.workspaces:
    parent: logger.channel_base
    arguments: ['workspaces']
  Psr\Log\LoggerInterface $loggerWorkspaces: '@logger.channel.workspaces'
```

The alias is `@logger.channel.workspaces` which look up the definition as `logger.channel.workspaces`. Given in:

```php
                // Check if this is an alias shortcut.
                // @link https://symfony.com/doc/4.4/service_container/alias_private.html#aliasing
                if (is_string($serviceDefinition)) {
                    $serviceDefinition = [
                        'alias' => str_replace('@', '', $serviceDefinition),
                    ];
                }
```

We resolve the alias before resolving the parent. We should resolve the alias and then the `parent`.
